service: weather

# provider:
#   name: aws
#   runtime: python3.6
#   environment:
#     apiKey: "${self:custom.secrets.dev.apikey}"
#     tmpLoc: "/tmp/"

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
         - "s3:PutObjectAcl"
       Resource:
         - "arn:aws:s3:::weather-denver/*"
  environment:
    apiKey: "${self:custom.secrets.dev.apikey}"
    tmpLoc: "/tmp/"

functions:
  weather:
    handler: handler.lambdaHandler
    events:
      - schedule:
          rate: cron(0 7 * * ? *)
          timezone: America/Denver

plugins:
  # - serverless-python-requirements
  - serverless-local-schedule
custom:
  # pythonRequirements:
  #   dockerizePip: non-linux
  secrets: ${file(secrets.yml)}
