service: weather

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
         - "s3:PutObjectAcl"
       Resource:
         - "arn:aws:s3:::weather-denver/*"
    -  Effect: "Allow"
       Action:
         - "SNS:Publish"
       Resource:
         - "arn:aws:sns:us-east-1:528165410097:Weather"
  environment:
    apiKey: "${self:custom.secrets.dev.apikey}"
    tmpLoc: "/tmp/"

functions:
  weatherNotifier:
    handler: handlerNotifier.lambdaHandler
    events:
      - schedule:
          rate: cron(0 7 * * ? *)
          timezone: America/Denver
  weatherDataOnly:
    handler: handlerDataOnly.lambdaHandler
    events:
      - schedule:
          rate: cron(0 * * * ? *)
          timezone: America/Denver

plugins:
  - serverless-local-schedule
custom:
  secrets: ${file(secrets.yml)}
